# Base image from NVIDIA Jetson L4T with ROS2 Humble pre-installed
FROM fablab_drone_01:latest
LABEL maintainer="eiu_drone_fablab01"

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /home

# Cài đặt các gói hệ thống cần thiết
RUN apt-get update && apt-get install -y \
apt-utils \
python3-pip \
nano gedit \
net-tools usbutils \
cmake make g++ \
pkg-config \
libgtk2.0-dev \
libjpeg-dev libpng-dev libtiff-dev \
libavcodec-dev libavformat-dev libswscale-dev \
libv4l-dev v4l-utils \
libopenblas-base libopenmpi-dev libomp-dev \
libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
libeigen3-dev \
dbus-x11 libsm6 libxext6 libxrender-dev libgl1-mesa-glx \
libcanberra-gtk-module libcanberra-gtk3-module \
python3-opencv \
geographiclib-tools \
libasio-dev libtinyxml2-dev \
libxml2-dev libxslt-dev python3-dev zlib1g-dev \
git wget \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

# Cài ROS2 tool & MAVROS
RUN apt-get update && apt-get install -y \
ros-humble-rviz2 \
ros-humble-tf-transformations \
ros-humble-joy \
ros-humble-joy-teleop \
ros-humble-cv-bridge \
ros-humble-rosbridge-server \
ros-humble-mavros \
ros-humble-mavros-extras \
ros-humble-mavros-msgs \
ros-humble-rqt-tf-tree \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

# Cài GeographicLib datasets
RUN wget https://raw.githubusercontent.com/mavlink/mavros/master/mavros/scripts/install_geographiclib_datasets.sh && \
chmod +x install_geographiclib_datasets.sh && \
./install_geographiclib_datasets.sh && \
rm install_geographiclib_datasets.sh

# Đảm bảo quyền truy cập dữ liệu
RUN chmod -R 755 /usr/share/GeographicLib/

# Cài đặt Micro-XRCE-DDS-Agent
RUN apt-get update && apt-get install -y \
git cmake make g++ \
libasio-dev libtinyxml2-dev \
&& apt-get clean && rm -rf /var/lib/apt/lists/*

# # Clone & Build Micro XRCE-DDS Agent
RUN git clone -b master https://github.com/eProsima/Micro-XRCE-DDS-Agent.git && \
cd Micro-XRCE-DDS-Agent && \
mkdir build && cd build && \
cmake .. && \
make -j$(nproc) && \
make install && \
ldconfig && \
cd ../.. && rm -rf Micro-XRCE-DDS-Agent
RUN pip3 install --upgrade pip setuptools wheel

RUN pip3 install "setuptools<60"
# Cài thư viện Python cần thiết
RUN pip3 install --no-cache-dir \
numpy scipy asyncio protobuf \
pyserial transforms3d websocket-client \
matplotlib jetson-stats MAVProxy \
grpcio future \
empy pyros-genmsg setuptools

# Source ROS2 on container start
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc

CMD ["/bin/bash", "-c", "source /opt/ros/humble/setup.bash && export $(dbus-launch) && exec bash"]
